### ISSUE TITLE
Great Project/Courtesy Note

### ISSUE THREAD

**Issue by techman83** [bbx10/SFX-I2S-web-trigger#2]
Yo, this project is great. Gave me a great headstart on my own. 

I grabbed the core parts and turned them into libraries which can be used with Platform IO
https://github.com/techman83/esp8266-wavplay
https://github.com/techman83/esp8266-wavspiffs

Thanks!

**Comment by bbx10** [comment]
Thanks, splitting the useful bits in to libraries is a good idea!

**Comment by techman83** [comment]
My first attempt at doing as such! (with C++ at least). Makes for a stupidly small amount of code to write a [doorbell](http://www.techman83.me/hardware/2017/06/04/dont_underestimate_the_doorbell.html).
